- name: fix /etc/network/interfaces - set IPv6 address (if defined)
  template: src=template/interfaces.j2 dest=/etc/network/interfaces
  become: yes
  when: ip6 is defined

- name: Restart all (but 'lo') interfaces (ETA 3.25 seconds)
  become: yes
  shell: "/sbin/ifdown --exclude=lo -a; sleep 1; /sbin/ifup --exclude=lo -a"
  changed_when: false
