- name: Ensure sudoers.d is enabled
  lineinfile: >
    dest=/etc/sudoers
    regexp='^#includedir /etc/sudoers.d'
    line='#includedir /etc/sudoers.d'
    state=present backup=yes

- name: Set up password-less sudo for admin users
  copy: >
    content="%{{ ssh_groups }} ALL=(ALL) NOPASSWD:ALL\nDefaults    env_keep+=SSH_AUTH_SOCK\n"
    dest=/etc/sudoers.d/admin
    owner=root group=root mode=0440

- name: Strict SSH access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
    validate='/usr/sbin/sshd -t -f %s'
  with_items:
    - { key: 'PubkeyAuthentication',   value: 'yes'}
    - { key: 'ChallengeResponseAuthentication', value: 'no'}
    - { key: 'PermitRootLogin',        value: 'without-password'}
    - { key: 'PasswordAuthentication', value: 'no'}
  # - { key: 'AllowGroups',            value: '{{ ssh_groups }}' }
    - { key: 'MaxAuthTries',           value: "2"}
    - { key: 'LoginGraceTime',         value: "6"}
    - { key: 'MaxSessions',            value: "5"}
    - { key: 'MaxStartups',            value: "10:30:60"}
    - { key: 'Port',                   value: '{{ ssh_port }}' }
  notify: restart sshd
